// examples/react/src/Checkbox.js
/* eslint-disable */

import React, {Component, PropTypes} from 'react';
import PureRenderMixin from 'react-addons-pure-render-mixin';
import {Set as ImmutableSet} from 'immutable';
// lol super hack
import MDLCheckbox from '../../../packages/mdl-checkbox';
import '../../../packages/mdl-checkbox/mdl-checkbox.scss';

export default class Checkbox extends Component {
  static propTypes = {
    checked: PropTypes.bool,
    indeterminate: PropTypes.bool,
    onChange: PropTypes.func,
    labelId: PropTypes.string
  }

  static defaultProps = {
    checked: false,
    indeterminate: false,
    onChange: () => {}
  }

  state = {
    classes: new ImmutableSet(),
    checkedInternal: false,
    indeterminateInternal: false
  }
  classesToAdd = new ImmutableSet();
  classesToRemove = new ImmutableSet();
  shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this);

  render() {
    return (
      <div ref="root" className={`md-checkbox ${this.state.classes.toJS().join(' ')}`}>
        <input ref="nativeCb"
               type="checkbox"
               className="md-checkbox__native-control"
               ariaLabelledBy={this.props.labelId}
               checked={this.state.checkedInternal}
               onChange={evt => {
                 this.setState({
                   checkedInternal: this.refs.nativeCb.checked,
                   indeterminateInternal: false
                 });
                 this.props.onChange(evt);
               }}/>
        <div className="md-checkbox__frame"></div>
        <div className="md-checkbox__background">
          <svg version="1.1"
               className="md-checkbox__checkmark"
               xmlns="http://www.w3.org/2000/svg"
               viewBox="0 0 24 24">
            <path className="md-checkbox__checkmark__path"
                  fill="none"
                  stroke="white"
                  d="M4.1,12.7 9,17.6 20.3,6.3"/>
          </svg>
          <div className="md-checkbox__mixedmark"></div>
        </div>
      </div>
    );
  }

  componentDidMount() {
    this.initMdlCheckbox_();
  }

  componentWillUnmount() {
    // From MDLCheckboxMixin
    this.removeEventListeners();
  }

  componentWillReceiveProps(props) {
    if (props.checked !== this.props.checked) {
      this.setState({checkedInternal: props.checked, indeterminateInternal: false});
    }
    if (props.indeterminate !== this.props.indeterminate) {
      this.setState({indeterminateInternal: props.indeterminate});
    }
  }

  componentDidUpdate() {
    if (this.refs.nativeCb) {
      this.refs.nativeCb.indeterminate = this.state.indeterminateInternal;
    }
  }
}
MDLCheckbox.mixInto(Checkbox, {
  addClass(className) {
    this.setState(prevState => ({
      classes: prevState.classes.add(className)
    }));
  },
  removeClass(className) {
    this.setState(prevState => ({
      classes: prevState.classes.remove(className)
    }));
  },
  addEventListener(type, listener) {
    if (this.refs.root) {
      this.refs.root.addEventListener(type, listener);
    }
  },
  removeEventListener(type, listener) {
    if (this.refs.root) {
      this.refs.root.removeEventListener(type, listener);
    }
  },
  addNativeCheckboxListener(type, listener) {
    if (this.refs.nativeCb) {
      this.refs.nativeCb.addEventListener(type, listener);
    }
  },
  removeNativeCheckboxListener(type, listener) {
    if (this.refs.nativeCb) {
      this.refs.nativeCb.removeEventListener(type, listener);
    }
  },
  getNativeCheckbox() {
    if (!this.refs.nativeCb) {
      throw new Error('Invalid state for operation');
    }
    return this.refs.nativeCb;
  },
  forceLayout() {
    if (this.refs.nativeCb) {
      this.refs.nativeCb.offsetWidth;
    }
  },
  isAttachedToDOM() {
    // Return true??
    return Boolean(this.refs.nativeCb);
  }
});

// examples/vue/src/v-mdl-checkbox/Checkbox.vue

<template>
<div ref="root" class="mdl-checkbox" :class="classes">
  <input ref="native"
         type="checkbox"
         class="mdl-checkbox__native-control"
         @change="fireEvent"
         :checked="value"
         :id="id"
         :aria-labelledby="labelId" />
  <div class="mdl-checkbox__background">
    <svg version="1.1" class="mdl-checkbox__checkmark"
         xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
         xml:space="preserve">
      <path class="mdl-checkbox__checkmark__path" fill="none" stroke="white"
            d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
    </svg>
  <div class="mdl-checkbox__mixedmark"></div>
</div>
</template>

<script lang="babel">
import { MDLCheckboxFoundation } from 'mdl-checkbox';

const { ANIM_END_EVENT_NAME } = MDLCheckboxFoundation.strings;

export default {
  props: ['id', 'labelId', 'value'],
  data () {
    return {
      classes: {},
      changeHandlers: [],
      foundation: null
    };
  },
  mounted () {
    let vm = this;
    this.foundation = new MDLCheckboxFoundation({
      addClass (className) {
        vm.$set(vm.classes, className, true);
      },
      removeClass (className) {
        vm.$delete(vm.classes, className);
      },
      registerChangeHandler (handler) {
        vm.changeHandlers.push(handler);
      },
      deregisterChangeHandler (handler) {
        let index = vm.changeHandlers.indexOf(handler);
        if (index >= 0) {
          vm.changeHandlers.splice(index, 1)
        }
      },
      registerAnimationEndHandler (handler) {
        vm.$refs.root.addEventListener(ANIM_END_EVENT_NAME, handler);
      },
      deregisterAnimationEndHandler (handler) {
        vm.$refs.root.removeEventListener(ANIM_END_EVENT_NAME, handler);
      },
      getNativeControl () {
        return vm.$refs.native;
      },

      isAttachedToDOM () {
        return Boolean(vm.$el);
      }
    });
    this.foundation.init();
  },
  beforeUnmount () {
    this.foundation.destroy();
  },
  methods: {
    fireEvent (event) {
      this.changeHandlers.forEach((h) => h(event));
      this.$emit('input', event.target.checked);
    }
  },
  computed: {
    labelId () {
      return this.id + '-label';
    }
  }
}

</script>

<style lang="scss">
@import 'mdl-checkbox/mdl-checkbox.scss';

</style>
